colorscheme desertex

add-highlighter global/line-numbers number-lines -hlcursor
add-highlighter global/list-chars show-whitespaces \
  -tab '»' -tabpad '·' -nbsp '•' -spc ' ' -lf ' '

add-highlighter global/overlong-line dynregex \
  '^[^\n]{%opt{autowrap_column}}([^\n])' 1:Error

declare-option str localkak %sh{echo $HOME/.local/kak}

source "%opt{localkak}/plugins/plug.kak/rc/plug.kak"
set-option global plug_install_dir "%opt{localkak}/plugins"

plug "andreyorst/fzf.kak"

map -docstring 'insert case-insensitive flag for searching by default' global normal / '/(?i)'
map -docstring 'fzf = <Ctrl+p>' global normal <c-p> ': fzf-mode<ret>'

hook global ModuleLoaded x11 %{
  set-option global termcmd 'term -e sh -c'
}

hook global BufWritePost .* 'git show-diff'
hook global BufOpenFile .* 'git show-diff'
map global user 'd' ': git diff %val{buffile}<ret>'

eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

hook global WinSetOption filetype=elixir %{
  set-option buffer autowrap_column 98
}

hook global WinSetOption filetype=java %{
  set-option buffer autowrap_column 120
}
